apiVersion: v1
kind: Namespace
metadata:
  name: insigna-express
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  namespace: insigna-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app
        image: ffiuca/insigna-test-express
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: cf-map-express
        - secretRef:
            name: secret-express
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express
spec:
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
      - name: mongodb-express
        image: mongo:nanoserver-ltsc2022
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-express
  namespace: insigna-express
spec:
  selector:
    app: express-app
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mongodb
  namespace: insigna-express
spec:
  selector:
    app: mongodb-express
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cf-map-express
  namespace: insigna-express
data:
  JWT_EXPIRES_IN: "1d"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-express
  namespace: insigna-express
type: Opaque
stringData:
  MONGODB_URI: "mongodb://admin:password@svc-mongodb.insigna-express.svc.cluster.local:27017/insigna-users?authSource=admin"
  JWT_SECRET: "insigna-jwt-secret-change-in-production"
  MONGODB_URI_TEST: "mongodb://admin:password@svc-mongodb.insigna-express.svc.cluster.local:27017/insigna-users-test?authSource=admin"
